
before_script:
   - docker info

build_image:
   script:
     - env
     - docker build -t firewah:${stuff} .
     - docker run --rm firewah:${stuff}rake test


# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
#before_script:
#  - ruby -v                                   # Print out ruby version for debugging
  # Uncomment next line if your rails app needs a JS runtime:
  # - apt-get update -q && apt-get install nodejs -yqq
#  - gem install bundler  --no-ri --no-rdoc    # Bundler is not installed with the image
#  - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby

#rails:
#  script:
#  - bundle exec rake test

# This deploy job uses a simple deploy flow to Heroku, other providers, e.g. AWS Elastic Beanstalk
# are supported too: https://github.com/travis-ci/dpl
#deploy:
#  type: deploy
#  environment: production
#  script:
#  - gem install dpl
#  - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_PRODUCTION_KEY
