apiVersion: apps/v1
kind: Deployment
metadata:
  name: firewah
  labels:
    app: firewah
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firewah
  template:
    metadata:
      labels:
        app: firewah
    spec:
      containers:
      - name: firewah
        image: gitlab.pd.o:4567/drule/firewah:24
        ports:
        - name: http
          containerPort: 3000
        env:
          - name: REDIS_HOST
            value: redis-master.default.svc.cluster.local
          - name: REDIS_PORT
            value: "6379"
          - name: RACK_ENV
            value: production
      imagePullSecrets:
        - name: gitlab
